export const USERS_GETALL_REQUEST = 'USERS_GETALL_REQUEST'
export const USERS_GETALL_SUCCESS = 'USERS_GETALL_SUCCESS'
export const USERS_GETALL_FAILURE = 'USERS_GETALL_FAILURE'

export const USERS_GETONE_REQUEST = 'USERS_GETONE_REQUEST'
export const USERS_GETONE_SUCCESS = 'USERS_GETONE_SUCCESS'
export const USERS_GETONE_FAILURE = 'USERS_GETONE_FAILURE'

export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'

export const USERS_SIGNUP_REQUEST = 'USERS_SIGNUP_REQUEST'
export const USERS_SIGNUP_SUCCESS = 'USERS_SIGNUP_SUCCESS'
export const USERS_SIGNUP_FAILURE = 'USERS_SIGNUP_FAILURE'

export const SPACES_GETALL_REQUEST = 'SPACES_GETALL_REQUEST'
export const SPACES_GETALL_SUCCESS = 'SPACES_GETALL_SUCCESS'
export const SPACES_GETALL_FAILURE = 'SPACES_GETALL_FAILURE'