export const USERS_GETALL_REQUEST = 'USERS_GETALL_REQUEST'
export const USERS_GETALL_SUCCESS = 'USERS_GETALL_SUCCESS'
export const USERS_GETALL_FAILURE = 'USERS_GETALL_FAILURE'

export const USERS_GETONE_REQUEST = 'USERS_GETONE_REQUEST'
export const USERS_GETONE_SUCCESS = 'USERS_GETONE_SUCCESS'
export const USERS_GETONE_FAILURE = 'USERS_GETONE_FAILURE'

export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'

export const USERS_SIGNUP_REQUEST = 'USERS_SIGNUP_REQUEST'
export const USERS_SIGNUP_SUCCESS = 'USERS_SIGNUP_SUCCESS'
export const USERS_SIGNUP_FAILURE = 'USERS_SIGNUP_FAILURE'

export const SPACES_GETALL_REQUEST = 'SPACES_GETALL_REQUEST'
export const SPACES_GETALL_SUCCESS = 'SPACES_GETALL_SUCCESS'
export const SPACES_GETALL_FAILURE = 'SPACES_GETALL_FAILURE'

export const SPACES_GETONE_REQUEST = 'SPACES_GETONE_REQUEST'
export const SPACES_GETONE_SUCCESS= 'SPACES_GETONE_SUCCESS'
export const SPACES_GETONE_FAILURE = 'SPACES_GETONE_FAILURE'

export const SPACES_UPDATEONE_REQUEST = 'SPACES_UPDATEONE_REQUEST'
export const SPACES_UPDATEONE_SUCCESS= 'SPACES_UPDATEONE_SUCCESS'
export const SPACES_UPDATEONE_FAILURE = 'SPACES_UPDATEONE_FAILURE'

export const USERS_UPDATE_REQUEST = 'USERS_UPDATE_REQUEST'
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS'
export const USERS_UPDATE_FAILURE = 'USERS_UPDATE_FAILURE'

export const SPACES_RESERVE_REQUEST = 'SPACES_RESERVE_REQUEST'
export const SPACES_RESERVE_SUCCESS = 'SPACES_RESERVE_SUCCESS'
export const SPACES_RESERVE_FAILURE = 'SPACES_RESERVE_FAILURE'

export const SPACES_RERSERVE_SPACE_USER_REQUEST = 'SPACES_RERSERVE_SPACE_USER_REQUEST'
export const SPACES_RERSERVE_SPACE_USER_SUCCESS = 'SPACES_RERSERVE_SPACE_USER_SUCCESS'
export const SPACES_RERSERVE_SPACE_USER_FAILURE = 'SPACES_RERSERVE_SPACE_USER_FAILURE'

export const USERS_RETAKESPACE_REQUEST = 'USERS_RETAKESPACE_REQUEST'
export const USERS_RETAKESPACE_SUCCESS = 'USERS_RETAKESPACE_SUCCESS'
export const USERS_RETAKESPACE_FAILURE = 'USERS_RETAKESPACE_FAILURE'